### ISSUE TITLE
resourceWrap/resourceSet/rightsResource/rightsType/conceptID ergänzen/wiederherstellen

### ISSUE THREAD

**Issue by mokko** [mokko/zml2lido#10]
1.	Rechtsstatus für die Bilder (resourceWrap/resourceSet/rightsResource/rightsType/conceptID): Dieser fehlt nun, es ist aber ein Pflichtelement. Es muss in der conceptID ein Rechtehinweis bzw. eine Lizenz aus dem DDB-Lizenzkorb gewählt werden; Könnten Sie diese bitte in der nächsten Datenlieferung nachtragen oder mir sagen, wie er lauten soll und ich trage die Links nach.

**Comment by FrankvonHagel** [comment]
CC By-SA-NC sollange wir keine Freigabe für den Verzicht auf NC bekommen.
Daten waren ebenfalls CC-BY-NC-SA aufgrund der Beschreibungstexte (Insbessondere weil ggf. Texte aus Werkverträgen verwendet wurden für die es keine ONLINE-Freigabe gibt). Sollte aber meines Erachtens dringend diskutiert werden. Keine NC-Einschränkung für Beschreibungstexte und somit CC BY-NC

**Comment by FrankvonHagel** [comment]
Was hast du denn im lido:rightsWorkSet?
Ich hatte da nie ien Rights-Statement sondern nur 
<lido:rightsHolder>
						<lido:legalBodyID lido:type="concept-ID"
						                  lido:source="ISIL (ISO 15511)">DE-MUS-019118</lido:legalBodyID>
						<lido:legalBodyName>
							<lido:appellationValue>Ethnologisches Museum, Staatliche Museen zu Berlin</lido:appellationValue>
						</lido:legalBodyName>
						<lido:legalBodyWeblink>http://www.smb.museum/em</lido:legalBodyWeblink>
					</lido:rightsHolder>
				</lido:rightsWorkSet>
			</lido:rightsWorkWrap>
