### ISSUE TITLE
Anzeige Status

### ISSUE THREAD

**Issue by FrankvonHagel** [mokko/zml2lido#100]
Bei längeren Prozessen wäre es hilfreich wenn der Status angezeigt würde 15% von 100 ... egal was oder wie.

     Hauptsache es wird deutlich das etwas geschieht....

Bei einer längeren Wartezeit (>5 Minuten) wächst die Unsicherheit ob sich nicht das Programm aufgehängt hat....

**Comment by mokko** [comment]
Das betrifft mpApi

**Comment by mokko** [comment]
Ich schließe das hier. Weiß auch nicht, wie das mit vertretbarem Aufwand im jetzigen mpApi realisierbar ist. Würde auf asynchrones mpApi warten.
