### ISSUE TITLE
lido:objectRelationWrap / subject /concept = zu

### ISSUE THREAD

**Issue by FrankvonHagel** [mokko/zml2lido#104]
kommt der Wert für das subject concept aus der DAtenbank MDS  jhabe hier "seltsame" Werte.

und ido:displaySubject ist gar nicht belegt

**Comment by mokko** [comment]
Kannst du mal bitte sagen, was du genau möchtest? 
- Was sind seltsame Werte?
- Wo soll displaySubject hin?

Du kannst dir gerne das aktuelle Mapping in objectRelationWrap.xsl selber ansehen. https://github.com/mokko/zml2lido/blob/e5f2e784ebe68039ed5e70efe9fbb21e20efe8fa/zml2lido/data/xsl/zml2lido/objectRelationWrap.xsl
