### ISSUE TITLE
Rechteauszeichung Bilder

### ISSUE THREAD

**Issue by FrankvonHagel** [mokko/zml2lido#106]
Ich denke die URL ist falsch für den Fall CC-BY-SA-NC ist dort die URI    
<lido:conceptID lido:source="CC" lido:type="URI">http://creativecommons.org/by-nc-sa/4.0/</lido:conceptID>
Richtig wäre 
https://creativecommons.org/licenses/by-nc-sa/4.0/

**Comment by FrankvonHagel** [comment]
Das CC-BY-NC-SA ist auch nur ein fallback für Bilder ohne Rechteangaben in MDS... mir ist unklar ob es zukünftig nicht CC-BY-SA also https://creativecommons.org/licenses/by-sa/4.0/ als fallback sein sollte.

**Comment by mokko** [comment]
PS: Ich mache jetzt keine andere Lizenz als Default bis das nicht auch in recherche.smb umgestellt ist.
