### ISSUE TITLE
Export Orte, Fehlende Ortstypen in der LIDO Transformation

### ISSUE THREAD

**Issue by FrankvonHagel** [mokko/zml2lido#108]
Es scheinen nicht alle Orte ausgespielt zu werden.
Fundorte würde zum "LIDO:Event: Fund" gehören
und
Entstehungsort stilistisch würde zum "LIDO:Event: Herstellung" gehören
werden in LIDO nicht angegeben
Ich habe mal zwei Beispiele ausgegeben.
- https://recherche.smb.museum/detail/1374805
- https://recherche.smb.museum/detail/2312591

[2Beispiele.zip](https://github.com/mokko/zml2lido/files/11060512/2Beispiele.zip)

**Comment by mokko** [comment]
Das Fund Event ist implementiert. Ob es auch wie gewünscht funktioniert, muss ich testen.

**Comment by mokko** [comment]
Der DS https://recherche.smb.museum/detail/2312591 enthält tatsächlich einen Fundort, aber das LIDO nicht. Der Grund liegt wohl daran, dass der Ort nciht im eigentlichen Feld eingetragen ist

**Comment by mokko** [comment]
zml
```
<dataField dataType="Varchar" name="DetailsTxt">
  <value>Meistersfelde (Gęsiki), Woje. Warmińsko-Mazurskie, Polen</value>
</dataField>
```

xslt versucht schon DetailsTxt auszuwerten. Funktioniert aber wohl nicht
```
	<xsl:variable name="geoname">
		<xsl:choose>
			<xsl:when test="$geopicker eq 'PlaceVoc' 
				or $geopicker eq 'PlaceILSVoc'">
				<xsl:value-of select="z:vocabularyReference[@name eq $geopicker]/z:vocabularyReferenceItem/z:formattedValue"/>
			</xsl:when>
			<xsl:when test="$geopicker eq 'DetailsText'">
				<xsl:value-of select="z:dataField[@name='DetailsTxt']/z:value"/>
			</xsl:when>
		</xsl:choose>
	</xsl:variable>
```

**Comment by mokko** [comment]
Das Problem war an anderer Stelle und zwar bei der Definition der Variable placesN, die eigentlich nur nicht-Orte wie Etrhnien herausgefiltern sollte, tatsächlich aber alle Orte ohne eine geogr.Bezeichnung herausgefiltert hat. Das ganze beheben wir mit dem kommenden Commit 65b0f17

**Comment by mokko** [comment]
65b0f17
