### ISSUE TITLE
event Provenance event - http://terminology.lido-schema.org/lido00227

### ISSUE THREAD

**Issue by FrankvonHagel** [mokko/zml2lido#110]
im Modul Porvenienz von RIA können Provenienzangaben im Reiter2 Grunddaten unter "Freigabe=Provenienzschritt freigegeben für SMB-digital" für die Veröffentlichung freigegeben werden. (OwnApprovalVoc ID1813607)
Sofern diese Freigabe erfolgt ist könnten wir mit den Daten das Provenance event - http://terminology.lido-schema.org/lido00227 bilden. 

Andernfalls - falls vorhanden -weiterhin nur die Erwerb.Notiz (Typ=Ausgabe

**Comment by mokko** [comment]
bisher exportieren wir nur PK, Objekte und Assets, also keine Provenienz

**Comment by FrankvonHagel** [comment]
Richtig nicht das Provenienzmodul nur die Erwerbungsnotiz Typ=Ausgabe aus dem Objektmodul und das ist der letzte Provenienzschritt

                <lido:eventType>
                     <lido:conceptID lido:type="URI" lido:source="LIDO-Terminologie">http://terminology.lido-schema.org/lido00001</lido:conceptID>
                     <lido:term xml:lang="de">Erwerb</lido:term>
                     <lido:term xml:lang="en">Acquisition (Activity)</lido:term>
                     
                  </lido:eventType>
                  <lido:eventDescriptionSet>
                     <lido:descriptiveNoteValue xml:lang="de" lido:encodinganalog="ErwerbNotizAusgabe">erworben am 6.12.1906 als Geschenk eines ungenannten Kunstfreundes</lido:descriptiveNoteValue>

**Comment by mokko** [comment]
Ich den letzten Schritt der Provenienz seit einiger Zeit Erwerbinformationen und wir sollten den tatsächlich ausgeben.
Wir sollten das Feld in der Tat ausgeben und tun das auch schon. Beim gegenwärtigen Van Gogh DS sieht das so aus
```
<lido:eventSet>
   <lido:displayEvent xml:lang="de">Erwerb</lido:displayEvent>
   <lido:event>
      <lido:eventType>
         <lido:conceptID lido:type="URI" lido:source="LIDO-Terminologie">http://terminology.lido-schema.org/lido00001</lido:conceptID>
         <lido:term xml:lang="de">Erwerb</lido:term>
         <lido:term xml:lang="en">Acquisition (Activity)</lido:term>
         <!--beschreibt den Erwerb des Objekts durch die verwaltende Institution-->
      </lido:eventType>
      <lido:eventDescriptionSet>
         <lido:descriptiveNoteValue xml:lang="de" lido:encodinganalog="ErwerbNotizAusgabe">erworben am 6.12.1906 als Geschenk eines ungenannten Kunstfreundes</lido:descriptiveNoteValue>
      </lido:eventDescriptionSet>
   </lido:event>
</lido:eventSet>

```
