### ISSUE TITLE
Online Beschreibungstext

### ISSUE THREAD

**Issue by FrankvonHagel** [mokko/zml2lido#111]
In den LIDO Export wird nur der Beschreibungstext mit dem TYP = "Online Beschreibung" exportiert.
Beschreibungstexte ohne Angabe eine Types werden nicht exportiert.

**Comment by mokko** [comment]
Das ist richtig so. Sie werden auch nur dann bei Recherche ausgespielt. Wir sollten nur solche online Beschreibungstexte an Portale weitergeben.
