### ISSUE TITLE
UDC/AAT in LIDO classification

### ISSUE THREAD

**Issue by mokko** [mokko/zml2lido#2]
Frank möchte UDC und AAT in LIDO. AAT steht verfügbar im Netz, da sollte also etwas möglich sein, ist nur gerade nicht höchste Priortät. Ich gehe dabei davon aus, dass der Sachbegriff auf AAT zu mappen ist.

Er schreibt:

> Zudem werden seitens europeana noch kontextuelle Anreicherungen gewünscht die jedoch in der Regel immer händisch reingemappt werden. Dabei stammen die Terme der UniversalClassification von UDC und die ObjektClassifikation aus AAT.

```
       <lido:classificationWrap>
          <lido:classification lido:type="universal classification">
            <lido:term xml:lang="de"/>
          </lido:classification>
          <lido:classification lido:type="object classification">
            <lido:term lido:addedSearchTerm="no" xml:lang="de"/>
          </lido:classification>
```

**Comment by FrankvonHagel** [comment]
Wenn du mir eine Liste gibst mache ich dir die URLs übers Wochenende.

**Comment by mokko** [comment]
Dieses Wochenende schaffe ich nicht. Ich hab Konferenz Mo-Fr 12h Tage

**Comment by mokko** [comment]
Das ist noch offen. Um es noch mal zu wiederholen: 
* wir wollen AAT & UDC in lido:classification. D.h. Dort stehen dann die internen/lokalen Begriffe und die angereicherten.
* grundsätzlich wollen wir Ria:Suchbegriffe auf AAT/UDT Mappen,
* wir könnten uns aber auch exotischere Mappings mit Objekttyp und Institution und Bereich nach dem Motto "wenn aus dem EM, dann ethnologisches Objekt" vorstellen

**Comment by mokko** [comment]
Franks Kandidaten für generische/allgemeine AAT Labels:
* Midas-Objekt= https://www.wikidata.org/wiki/Q838948 | http://vocab.getty.edu/aat/300133025 = work of art oder works of art
* Allgemein-ÄMP= http://vocab.getty.edu/aat/300234110 = archaeological object
* ethnographic objects http://vocab.getty.edu/aat/300234108 verpassen.
Bei den object genres (object classifications) http://vocab.getty.edu/aat/300185712 ist der AAT sehr wild

**Comment by mokko** [comment]
Also wie wäre es, wenn wir ein generischen/allgemeinen term vergeben und ein spezifisches pro Sachbegriff.

**Comment by mokko** [comment]
example for generic AAT term
```
               <lido:classification>
                  <lido:conceptID lido:source="AAT" lido:type="uri">http://vocab.getty.edu/aat/300417586</lido:conceptID>
                  <lido:term xml:lang="en" lido:addedSearchTerm="yes">art</lido:term>
               </lido:classification>

```

**Comment by mokko** [comment]
https://github.com/mokko/zml2lido/commit/1b96cc12d969283c623501444285b3892e2cf2a4

I will make a new issue for specific AAT
