### ISSUE TITLE
Sind Entwerfer immer an der Herstellung beteiligt?

### ISSUE THREAD

**Issue by mokko** [mokko/zml2lido#33]
```
        <moduleReference name="ObjPerAssociationRef" targetModule="Person" multiplicity="M:N" size="1">
          <moduleReferenceItem moduleItemId="360" seqNo="0">
            <formattedValue language="en">Hans Looschen (23.06.1859 - 11.02.1923), Entwerfer</formattedValue>
            <dataField dataType="Long" name="SortLnu">
              <value>1</value>
              <formattedValue language="en">1</formattedValue>
            </dataField>
            <vocabularyReference name="RoleVoc" id="30423" instanceName="ObjPerAssociationRoleVgr">
              <vocabularyReferenceItem id="4378312" name="Entwerfer">
                <formattedValue language="en">Entwerfer</formattedValue>
              </vocabularyReferenceItem>
            </vocabularyReference>
          </moduleReferenceItem>
        </moduleReference>
```

Ich gehe mal davon aus und führe also Entwerfer auch unter Herstellung auf.

**Comment by FrankvonHagel** [comment]
Also ich würde die Entwerfer in das Event  http://terminology.lido-schema.org/lido00224 Designing  bzw Entwurf packen

**Comment by FrankvonHagel** [comment]
Leider sind die Event zuordnung nicht immer eingetragen, du kannst aber auch nicht ausschließlich über die Rollen gehen siehe UUID 2600947 hier wird die Marie Schulz nicht ausgegeben. Ihre Rolle ist Zeichnerin... Damit würden wir alle Personen NICHT bekommen deren Rollen im PK nicht eingetragen sind oder alle als Zeichnerinne falsch zuordnen die auch bildhauerisch tätig waren...

**Comment by mokko** [comment]
Ich verstehe das nicht.

**Comment by mokko** [comment]
https://github.com/mokko/zml2lido/commit/9400ec5fc93e85e97cb1d907c683119723549855

habe LIDO auf saasweb schon entsprechend korrigiert.müsstest du an der Uhrzeit sehen
