### ISSUE TITLE
Specific AAT term mapping

### ISSUE THREAD

**Issue by mokko** [mokko/zml2lido#36]
#2 provides some context. In this issue we try to do only a specific mapping from Sachbegriff to AAT using a mapping that is stored as part of the mapping on disk, e.g. in vocmap.xml

**Comment by mokko** [comment]
the mechanism is there only the terms are still missing. Now I want to write SPARQL etc. to extract the terms from a file on disk.

**Comment by FrankvonHagel** [comment]
Frage zum Titel, dies ist ja das Fashion.Mapping mit AAT Termen. Siehst du eine Möglichkeit zukünftig direkter auf die Daten im Vokabularmodul zugreifen zu können.....
