### ISSUE TITLE
include existing English fields into LIDO

### ISSUE THREAD

**Issue by mokko** [mokko/zml2lido#37]
step one to create multi-language is to write existing english fields into lido.

Which fields have English content?
* dateType = datierung engl.

**Comment by mokko** [comment]
Ich verstehe das nicht mehr. Ich lasse es noch ein bisschen stehen.

**Comment by FrankvonHagel** [comment]
Mehrsprachigkeit wurde im ALTEM MDS (Klassik) in einigen Feldern dadurch erreicht das es Qulifikatoren mit dem Zusatz ...engl. oder ...fr gab z.B. bei Datierung diesen Qulifikator gibt es bei ObjDateGrp.TypeVoc immer noch. Er wäre aber in vielen Fällen wegen des mehrsprachigen Vokabularmoduls nicht mehr notwendig. AUSNAHME dürfte die Dateirung sein wegen der unterschiedlichen "verbalen englischen Schreibweisen"

**Comment by mokko** [comment]
Ich glaube, es gibt keinen prinzipiellen Unterschied zwischen Klassik und RIA bei Englischen Felder (Qualis). Und die Sprachauszeichnung von RIA ist auch nicht zuverlässig.

**Comment by FrankvonHagel** [comment]
Doch sofern die Begriffe aus dem Vokabular-Modul stammen gibt es dort ja die Möglichkeit der unterschiedlichen Sprachausgaben für einen Term.

**Comment by mokko** [comment]
Du sagst mir konkret, wo etwas fehlt.
