### ISSUE TITLE
New URL for  <lido:recordInfoLink>

### ISSUE THREAD

**Issue by FrankvonHagel** [mokko/zml2lido#42]
The prefix of the URL in <lido:recordInfoLink lido:formatResource="html">https://recherche.smb.museum/detail/606189lido:recordInfoLink> will changed into  <lido:recordInfoLink lido:formatResource="html">https://id.smb.museum/detail/2664575</lido:recordInfoLink>
Mr. Anzolin will establish this redirect - maybe next week - and inform us if done. 
Please change this URL in the LIDO export if it is done.

**Comment by FrankvonHagel** [comment]
The Domain https://id.smb.museum ist eingerichtet Herr Anzolin schreibt nun das scrip für die Umleitung auf Recherche-URL
Es soll folgende URL umgeleitet werden https://id.smb.museum/object/2664575 auf https://recherche.smb.museum/detail/606189 .
Please implement this URL in  the lido transformation <lido:recordInfoLink lido:formatResource="html">https://id.smb.museum/object/2664575</lido:recordInfoLink>

**Comment by mokko** [comment]
Implementiert. Habe ein Beispiel per Email geschickt, aber noch nicht geguckt, ob du schon geantwortet hast.

**Comment by FrankvonHagel** [comment]
sieht gut aus
