### ISSUE TITLE
IMAGE URL <lido:linkResource lido:formatResource="image/jpeg">

### ISSUE THREAD

**Issue by FrankvonHagel** [mokko/zml2lido#43]
Question: does it make sense from 
<lido:linkResource lido:formatResource="image/jpeg">https://recherche.smb.museum/images/.....
to 
<lido:linkResource lido:formatResource="image/jpeg">https://id-digital.smb.museum/....
redirect?

There may soon also be 
- <lido:linkResource lido:formatResource="3D/ply">https://recherche.smb.museum/3d/.....
- <lido:linkResource lido:formatResource="pdf">https://recherche.smb.museum/pdf/.....
- <lido:linkResource lido:formatResource="video/mov">https://recherche.smb.museum/video3d/.....
can all of these become <lido:linkResource lido:formatResource="image/jpeg">https://id-digital.smb.museum/.... because there should be no duplicate numbers in the digital assets, whether image, video or otherwise?

**Comment by mokko** [comment]
Die Ansolin links sind langsamer, brauchen mehr http requests, um zur Datei zu führen, sind nur logisch besser. Wenn die aber zur jpg führen, könnten wir uns das lästige Raten einer URL sparen.

Und du sagst andere Dateitypen kommen auch?

**Comment by mokko** [comment]
Von wegen Duplikate: Alles im Digital Asset Raum hat natürlich eine distinkte ID, ob das nun pdf ist oder jpg etc.

**Comment by FrankvonHagel** [comment]
Müssen ja kommen, ihr habt mpeg, mp3 und PDF inklusive 3-D PDFs (das sollte man ändern) finde ich. Wenn wir siocher sind das wirklich distinke IDs verwendet werden könnte man auch mit einer eigenen SUB-Domain für Digital-Assets arbeiten. da wir aber vorab die IDs im Domain-Umlenkungsprozeß nicht haben.... Schwierig.

**Comment by FrankvonHagel** [comment]
Ich möchte jetzt das PRINZIP der URLs für Datensätze und Digital Asets festklopfen, um Vermutlich wäre es sinnvoll zu einem Späteren Zeitpunkt nicht nur einen Umlenkungsdienst einzurichten sondern einen RICHTIGEN Resolver aufzubauen der dann aich schnelle die Umleitungen und URLs anbieten könnte.

**Comment by FrankvonHagel** [comment]
Ich habe mir nochmals die letzten Exporte angeschaut und mir fällt auf das keine URLs im Lido:resource sind, sondern "nur" der Bildname zudem glaube ich wir sollten Herrn Katz als Fotograf und nicht als Urheber bezeichnen.... oder?
<lido:resourceSet lido:sortorder="10">
<lido:resourceID lido:label="Bild" lido:type="local" lido:source="SMB/ObjID/AssetID">de-MUS-018313/2600947/5919885</lido:resourceID>
<lido:resourceRepresentation lido:type="Provided image">
<lido:linkResource lido:formatResource="image/jpeg">**5919885.jpg**</lido:linkResource>

**Comment by mokko** [comment]
Ok. Guck ich mir morgen an. Der interne Dateiname sollte sich mit dem gleichen Testverfahren in eine externe url verwandeln lassen, das wir schon an anderer Stelle verwenden.

**Comment by mokko** [comment]
Aus juristischer Sicht ist der Fotograf normalerweise der Urheber eines Bildes. Ich schreibe da aber hin, was Du möchtest. Ich kann den Kontext jetzt gerade nicht so richtig einschätzen. RIA Feld heißt Urheber/Fotograf, richtig?

**Comment by FrankvonHagel** [comment]
ja, MulPhotographerPerRef wobei idealerweise müsse man den Namen dann aus dem Personen/Körperschaft holen dann hätte mach auch Zugriff auf die weiteren Informationen.

**Comment by mokko** [comment]
(1) Ich ersetze die internen Dateinamen in linkResource mit dem LinkChecker Script, d.h. erst die Dateien mit -links.onlyPub.lido.xml haben die (externen) URLs
(2) Stand heute scheinen die neuen URLs für Assets noch nicht zu funktionieren. Habe https://id.smb.museum/asset/5919885.jpg und https://id.smb.museum/multimedia/5919885.jpg ausprobiert.
(3) Fotograf ist nicht besser als Urheber; Fotograf ist speziell für Fotos, wir haben aber auch andere Medientypen (pdf, Film etc.); Urheber ist aber m.E. auch bei Fotos richtig. Wenn du jetzt möchtest, dass ich medienspezifisches Mapping hier einbaue, ist das außerhalb von RIA.
