### ISSUE TITLE
vital dates

### ISSUE THREAD

**Issue by mokko** [mokko/zml2lido#44]
```
<lido:vitalDatesActor>
    <lido:earliestDate/>
    <lido:latestDate/>
 </lido:vitalDatesActor>

```
empty elements are fixed, but LIDO cannot take textual info as shown in screensho
<img width="365" alt="screen" src="https://user-images.githubusercontent.com/275316/154792338-f9d35a47-b920-4f6a-ae6e-f912c639a935.png">
t

**Comment by FrankvonHagel** [comment]
Das wäre dann rein Display und 
<lido:vitalDatesActor>
   <lido:earliestDate/>
   <lido:latestDate/>
</lido:vitalDatesActor>
blieben leer

**Comment by mokko** [comment]
Ja, so sehe ich das auch. Was RIA hat, ist so etwas wie Display Feld. Das scheint es aber Lido Spec nicht zu geben. 
(Natürlich muss man leere vitalDates nicht anzeigen und vitalDates sind nur leer, wenn in RIA wirklich keine von und bis Daten eingegeben.)

**Comment by FrankvonHagel** [comment]
Tja wurde leider in LIDO1.1. auch nicht umgesetzt... http://lido-schema.org/schema/v1.1/lido-v1.1.html#vitalDatesActor Könnte man also das Datum nur noch in () hinter dem Namen im DisplayAcrtor packen wie es manche Kunsthistoriker machen.
