### ISSUE TITLE
relatedWorks are not online

### ISSUE THREAD

**Issue by mokko** [mokko/zml2lido#45]
Ich kann zwar nette relatedWorks elemente erzeugen, diese sind aber potenziell nicht online. Dann versuche ich sie im LinkChecker zu prüfen, aber die http response, die ich vom Frontend bekomme, ist immer positiv. Also no go. Man könnte die [api.recherche ](https://api.smb.museum) nehmen oder gleich in RIA nachgucken. Das ist mir aber etwas viel für dieses Wochenende. Also schalte ich die relatedWorksWrap erst einmal aus.
```
<lido:relatedWorksWrap>
   <lido:relatedWorkSet>
      <lido:relatedWork>
         <lido:displayObject>Teil von: 2020,014/001-124, Konvolut, Kostüm- und Modezeichnungen, um 1925 - 1935, Marie Schulz (? - nach 1960)</lido:displayObject>
         <lido:object>
            <lido:objectWebResource>https://recherche.smb.museum/detail/2588589</lido:objectWebResource>
            <lido:objectID lido:type="local" lido:source="OBJ.ID">2588589</lido:objectID>
            <lido:objectNote>Teil von: 2020,014/001-124, Konvolut, Kostüm- und Modezeichnungen, um 1925 - 1935, Marie Schulz (? - nach 1960)</lido:objectNote>
         </lido:object>
      </lido:relatedWork>
      <lido:relatedWorkRelType>
         <lido:term xml:lang="de">Umfasst</lido:term>
      </lido:relatedWorkRelType>
   </lido:relatedWorkSet>
</lido:relatedWorksWrap>
```

**Comment by FrankvonHagel** [comment]
Danke Dir....

**Comment by mokko** [comment]
Inzwischen sind nur noch die relatedWorks enthalten, die SMB freigegeben sind.

**Comment by mokko** [comment]
Heute wieder verändert. Es gibt jetzt Literaturhinweise, die online sind, egal, ob sie online sind oder nicht
