### ISSUE TITLE
resouceSet – <lido:linkResource

### ISSUE THREAD

**Issue by FrankvonHagel** [mokko/zml2lido#47]
Anpassung von 
<lido:linkResource lido:formatResource="image/jpeg">https://recherche.smb.museum/images/5919885_2500x2500.jpg</lido:linkResource>
sobald neue ID-URL für digitalAssets aktiv.

**Comment by FrankvonHagel** [comment]
URL für digital assets: https://id.smb.museum/digital-asset/6114080 also https://id.smb.museum/digital-asset/BILD-ID

**Comment by mokko** [comment]
habe ich heute gemacht
