### ISSUE TITLE
Feld Inhalt/Ansicht wird jetzt immer ausgespielt

### ISSUE THREAD

**Issue by FrankvonHagel** [mokko/zml2lido#49]
Es ist auch nicht für recherche.smb.museum definiert http://tabula.smb.spk-berlin.de/w/Onlinesammlungen_der_SMB

**Comment by mokko** [comment]
Dann schreibe ich dir dafür einen Filter. Muss ich noch machen.

**Comment by mokko** [comment]
Zusammenfassung: Manche Nutzer*innen wollen das Feld haben anderen. Neue Lösung: Ich spiele es immer aus und Frank kann es wiederherauslöschen, wenn er es nicht braucht. Dazu liefere ich im einen Filter.

**Comment by mokko** [comment]
e46c3d3

**Comment by mokko** [comment]
zml2lido/data/xsl/zml2lido/resourceWrap.xsl
<xsl:apply-templates select="z:dataField[@name='MulSubjectTxt']/z:value"/>
```
<xsl:template match="z:dataField[@name='MulSubjectTxt']/z:value">
   <lido:resourceDescription>
	<xsl:value-of select="."/>
   </lido:resourceDescription>
</xsl:template>
```

**Comment by mokko** [comment]
Habe neuen Filter gemacht, aber noch nicht getestet
>dropResourceDescriptionInhaltAnsicht.xsl

**Comment by mokko** [comment]
Filter hinzugefügt und ein bisschen getestet.

**Comment by FrankvonHagel** [comment]
Ich habe eine Nachricht mit folgende Inhalt bekommen:
e46c3d3
Was bedeutet das, Ähnlich  (für mich) kryptische Buchstabenfolgen tauchen in Gihub Nachrichten öfters auf.

**Comment by mokko** [comment]
Das ist ein Kürzel für das Commit, mit dem ich das Problem aus diesem Issue gelöst habe. Müsste man drauf flicken können und dann diff sehen.
