### ISSUE TITLE
URLs für LIDO-Export

### ISSUE THREAD

**Issue by FrankvonHagel** [mokko/zml2lido#50]
Zwar wurde der Start von Sammlung online nochmals verschoben aber ich denke dennoch sollten wir nun im LIDO Export auch die URLs der digital-assets mit der dauerhaften URL nutzen. und zwar wie folgt

URL: https://id.smb.museum/digital-asset/[ASSET-ID]

Für alle Digital Asset mit "Daten freigegeben smb-digital"
unter Angabe des Dateitypes. Der ist aber nur in Digtial Asset im DATEINAMEN (xyz.jpg) enthalten da im Feld Format in der Regel das Format der analogen Vorlage eingegeben ist.

Beispiel ObjectID=194398 (https://id.smb.museum/object/194398)
mit der digital assetID=3285370 (https://id.smb.museum/digital-asset/3285370 
hat im MDS unter Digital Asset das Format=6x7 und Mat./Tech.=Diafilm
der Dateiname lautet: I B 104 -A.JPG

Soweit ich mich erinnere war im alten MDS  ein Feld "Dateiendung" enthalten das es nun nicht mehr gibt.

**Comment by mokko** [comment]
Cool. D.h. ich brauche die Dateiendung nicht mehr. D.h. ich kann wohl einen ganzen Schritt eliminieren und muss nicht mehr nachträglich die URLs für Assets raten/suchen.

**Comment by mokko** [comment]
c4cd3987d5c9bbb38a0b425d9227fc090988e32e
