### ISSUE TITLE
Ordnung Exporte im SPLIT

### ISSUE THREAD

**Issue by FrankvonHagel** [mokko/zml2lido#51]
Beim SPLIT werden die Dateien separiert und in einem Ordner mit dem ISIL-Nummer gepackt. GUT. 
Wenn aber mehrere Exporte einer Institution anstehen z.B. KB haben (Plakate und Design) vermischen sich dadurch die Exporte – SCHLECHT.
Da müssten wir noch eine Lösung (Exportname in den Ordnernamen?) finden..

LG Frank

**Comment by mokko** [comment]
Kann ich in eigenem Order exportieren.

**Comment by mokko** [comment]
Als Folge davon muss du mir jetzt immer sagen, welche Daten du haben willst

Früher habe ich einfach FvH exportiert und jetzt muss ich die einzeln exportieren
FvH:
	getPack group 182397 KB-zeichnetMode
	getPack group 64396 KB-FruhePlakateI # Probleme mit Umlaut
	getPack group 154397 KKvanGoghWorldwide
	getPack group 246386 FvHFloten
#	pack

Plakate: # new 20221009
	getPack group 64396 KB-FruhePlakateI # Probleme mit Umlaut

Mode: # new 20221009
	getPack group 182397 KB-zeichnetMode

**Comment by FrankvonHagel** [comment]
getPack group 64396 KB-FruhePlakateI # Probleme mit Umlaut ? An welcher Stelle gibt es probleme mit Umlauten, im Gruppennamen? Dann sollten wir deren Verwendung an dieser stelle verbieten...
