### ISSUE TITLE
LIDO-Transformation Rechte record Rights

### ISSUE THREAD

**Issue by FrankvonHagel** [mokko/zml2lido#52]
Änderung der URI für Rechte Public Domain anstatt in lido:recordRights/lido:rightsType/lido:conceptID die URI: https://creativecommons.org/share-your-work/public-domain/cc0/ bitte die URI https://creativecommons.org/publicdomain/zero/1.0/ verwenden.

**Comment by mokko** [comment]
ok

**Comment by mokko** [comment]
done
