### ISSUE TITLE
LIDO-Event Erwerb erweitern um engl. Term

### ISSUE THREAD

**Issue by FrankvonHagel** [mokko/zml2lido#53]
<lido:eventType>
                     <lido:conceptID lido:type="URI" lido:source="LIDO-Terminologie">http://terminology.lido-schema.org/lido00001</lido:conceptID>
                     <lido:term xml:lang="de">Erwerb</lido:term>
                     <lido:term xml:lang="en">Acquisition (Activity)</lido:term>

**Comment by mokko** [comment]
kann ich machen

**Comment by mokko** [comment]
Frank, möchtest du die englischen Begriffe für folgende EventTypen heraussuchen? Ich glaube wir gebrauchen nicht alle, ich habe aber zu allen hier Dateien.

Aufführung
Auftrag
Ausgrabung
Ausstellung
Entwurf
Erwerb
Fund
Herstellung
Sammeln
Veröffentlichung

**Comment by mokko** [comment]
andere Übersetzungen sind schon vorhanden.

**Comment by FrankvonHagel** [comment]
Ich weiß nicht ob ich die Aufgabe richtig verstanden habe also habe ich sie einmal durchgespielt....

Aufführung erledigt -> http://terminology.lido-schema.org/lido00030 -> Performance
    closely matching | http://d-nb.info/gnd/4143388-9 (Aufführung)
    closely matching | http://vocab.getty.edu/aat/300069200 (performances (creative events))
    closely matching | https://www.wikidata.org/wiki/Q35140 (performance)
Auftrag erledigt -> http://terminology.lido-schema.org/lido00226 -> Commissioning =im Sinne Beauftragung
   closely matching | http://d-nb.info/gnd/4003557-8 (Auftrag)
   closely matching | http://www.wikidata.org/entity/Q566889 (order)
   exactly matching | http://vocab.getty.edu/aat/300393199 (commissions (work-related events))
Ausgrabung erledigt -> http://terminology.lido-schema.org/lido00033 -> Excavation
  closely matching | http://d-nb.info/gnd/4129464-6 (Ausgrabung)
  closely matching | http://vocab.getty.edu/aat/300053702 (excavation (process))
  closely matching | https://www.wikidata.org/wiki/Q959782 (excavation)
Ausstellung erledigt -> http://terminology.lido-schema.org/lido00225 -> Exhibition (Activity)
  exactly matching | http://vocab.getty.edu/aat/300054766 (exhibitions (events))
  closely matching | http://d-nb.info/gnd/4129601-1 (Ausstellung)
  exactly matching | http://www.wikidata.org/wiki/Q464980 (exhibition)
Entwurf erledigt -> http://terminology.lido-schema.org/lido00224 -> Designing
  related | http://vocab.getty.edu/aat/300102051 (designs (artistic concepts))
  broader | https://d-nb.info/gnd/4121208-3 (Entwurf)
  an unspecified match | http://www.wikidata.org/entity/Q560361 (Entwurf  \|  Draft document)
Erwerb erledigt. -> http://terminology.lido-schema.org/lido00001 -> Acquisition (Activity)
  closely matching | http://d-nb.info/gnd/4015451-8 (Erwerbung)
  closely matching | http://vocab.getty.edu/aat/300157782 (acquisition (collections management))
  broader | http://vocab.getty.edu/aat/300417634 (methods of acquisition)
  closely matching | https://d-nb.info/gnd/4212536-4 (Erwerb)
  related | http://vocab.getty.edu/aat/300077989 (purchasing)
Fund erledigt -> http://terminology.lido-schema.org/lido00002 -> Finding (Activity)
...
Herstellung erledigt -> http://terminology.lido-schema.org/lido00007 -> Production
   exactly matching | http://vocab.getty.edu/aat/300054713 (production)
   closely matching | http://d-nb.info/gnd/4159653-5 (Herstellung)
   exactly matching | http://www.wikidata.org/wiki/Q739302 (production)
Sammeln erledigt -> http://terminology.lido-schema.org/lido00010 -> Collecting
  exactly matching | http://vocab.getty.edu/aat/300077121 (collecting)
  exactly matching | http://d-nb.info/gnd/4051494-8 (Sammeln)
  exactly matching | http://www.wikidata.org/wiki/Q208165 (collecting)
Veröffentlichung erledigt -> http://terminology.lido-schema.org/lido00228 -> Publishing
   closely matching | http://d-nb.info/gnd/4187925-9 (Veröffentlichung)
   closely matching | http://vocab.getty.edu/aat/300054686 (publishing)

Es müssen nicht nur die LIDO-URIs angegeben werden . Es könnten auch noch andere URIs mitgeliefert werden. Ich habe diese einmal hinzugefügt... So ergibt sich eine Möglichkeit der Ontologiebildung, zumal auch Broader / Narrower Definitionen im LIDO vorhanden sind

**Comment by mokko** [comment]
Ich weiß nicht, ob mein Vokabularformat das kann. Muss das jetzt sein?

**Comment by FrankvonHagel** [comment]
Müssen muss das nicht, wäre vielleicht eine spätere Entwicklungsstufe.

**Comment by mokko** [comment]
Jetzt ist das Format folgendermaßen:
```		
<concept>
			<source lang="de">Bluse</source>
			<target name="aatUri">http://vocab.getty.edu/aat/300046133</target>
			<target name="fashionUri">http://thesaurus.europeanafashion.eu/thesaurus/10018</target>
</concept> 
```

Dann muss es demnächst so aussehen:
```		
<concept>
			<source lang="de">Bluse</source>
			<target name="aatUri">http://vocab.getty.edu/aat/300046133</target>
			<target relation="exactMatch" name="fashionUri">http://thesaurus.europeanafashion.eu/thesaurus/10018</target>
</concept>
```

ExactMatch dürfte default sein, also weg zu lassen.

Dann würde ich wohl noch ein Tool bauen, um die Datei in Excel zu bearbeiten, statt XML per Hand zu schreiben.

**Comment by mokko** [comment]
Wo schreibt man die Genauigkeit in Lido? Und willst du diese Synonyme wirklich bei Event types haben oder vielleicht bei subjects?

**Comment by mokko** [comment]
Ich mache lieber ein neues Issue

**Comment by FrankvonHagel** [comment]
Im LIDO 1.0 wird einfach das Feld concept-ID wiederholt. In 1.1 wurde nun ein SKOS-Element eingeführt. Das wäre vielleicht zunächst zu viel.
Die Definition wäre hier
https://cidoc.mini.icom.museum/working-groups/lido/lido-overview/about-lido/what-is-new-1-1/
Skos sähe so in 1.1. aus: 
  </lido:objectWorkType>
      
      <lido:objectWorkType lido:type="http://terminology.lido-schema.org/lido00767">
          <skos:Concept rdf:about="http://vocab.getty.edu/aat/300262491">
              <skos:prefLabel xml:lang="en">commemorative sculpture</skos:prefLabel>
              <skos:exactMatch>http://www.wikidata.org/wiki/Q3476510</skos:exactMatch>
         </skos:Concept>
         <lido:term lido:addedSearchTerm="yes">Gedenkskulptur</lido:term>
         <lido:term lido:addedSearchTerm="yes">Erinnerungsskulptur</lido:term>
      </lido:objectWorkType>
