### ISSUE TITLE
LIDO Erweiterung zur Ausgabe von Literatur (zunächst für KK-vanGogh)

### ISSUE THREAD

**Issue by FrankvonHagel** [mokko/zml2lido#54]
Für das van Gogh Projekt gibt es den Wunsch Literatur zu exportieren. Ich hoffe für spätere Akteuere diese Information auch ausgeben zu können. Bei mehreren Literaturangaben müssten die Sets wiederholt werden.

      <lido:objectRelationWrap>
        <lido:relatedWorksWrap>
          <lido:relatedWorkSet>
            <lido:relatedWork>
              <lido:displayObject/>
              <lido:object>
                <lido:objectNote lido:encodinganalog="" lido:type="Literatur">ObjLiteratureRef</lido:objectNote>
              </lido:object>
            </lido:relatedWork>
            <lido:relatedWorkRelType>
              <lido:conceptID lido:type="URI">http://terminology.lido-schema.org/lido00617</lido:conceptID>
              <lido:term lido:addedSearchTerm="no" xml:lang="ab">is documented in</lido:term>
            </lido:relatedWorkRelType>
          </lido:relatedWorkSet>
        </lido:relatedWorksWrap>
      </lido:objectRelationWrap>

Soweit ich das sehen haben wir keine "lido:objectID" für die Note oder sollten wir da die Object ID des Werkes wiederholen? Dann gerne mit local UUID und URN "https://id.smb.museum/object/[UUID]

**Comment by mokko** [comment]
generisches XML

``` 
       <moduleReference name="ObjLiteratureRef" targetModule="Literature" multiplicity="M:N" size="15">
          <moduleReferenceItem moduleItemId="210989" seqNo="0">
            <formattedValue language="en">Object: Ausst.-Kat. Madrid 2005</formattedValue>
            <vocabularyReference name="TypeVoc" id="30317" instanceName="LitObjectTypeVgr">
              <vocabularyReferenceItem id="30935" name="node_1286">
                <formattedValue language="en">Object</formattedValue>
              </vocabularyReferenceItem>
            </vocabularyReference>
          </moduleReferenceItem>
          <moduleReferenceItem moduleItemId="232299" seqNo="1">
            <formattedValue language="en">Object: Ausst.-Kat. Berlin 1996, P. 140-142, Cat. No. 48, S. 384</formattedValue>
            <dataField dataType="Varchar" name="CatalogueNumberTxt">
              <value>48, S. 384</value>
            </dataField>
            <dataField dataType="Varchar" name="PageRefTxt">
              <value>140-142</value>
            </dataField>
            <vocabularyReference name="TypeVoc" id="30317" instanceName="LitObjectTypeVgr">
              <vocabularyReferenceItem id="30935" name="node_1286">
                <formattedValue language="en">Object</formattedValue>
              </vocabularyReferenceItem>
            </vocabularyReference>
          </moduleReferenceItem>
```

**Comment by FrankvonHagel** [comment]
![image](https://user-images.githubusercontent.com/25053863/192500951-44186e58-41fa-4a75-8975-81fe4da892b1.png)

**Comment by FrankvonHagel** [comment]
Ok ich sehe es, mehr kannst du aus demObjektmodul nicht herausbekommen, ansonsten müsstes du noch das Literaturmopdul auslesen...
