### ISSUE TITLE
relatedWork bei Literaturhinweisen

### ISSUE THREAD

**Issue by mokko** [mokko/zml2lido#56]
```
 <lido:relatedWorkSet>
    <lido:relatedWork>
       <lido:displayObject>Hübner, Hans 2002</lido:displayObject>
       <lido:object>
          <lido:objectID lido:type="local" lido:source="LIT.ID">250434</lido:objectID>
       </lido:object>
    </lido:relatedWork>
    <lido:relatedWorkRelType>
       <lido:conceptID lido:type="URI">http://terminology.lido-schema.org/lido00263</lido:conceptID>
       <lido:term xml:lang="en">is related to</lido:term>
    </lido:relatedWorkRelType>
 </lido:relatedWorkSet>
```
@FrankvonHagel, wir haben jetzt mit den Literaturverweisen schlechte relatedWorks dokumentiert (vgl. oben). Bisher wolltest du, dass ich relatedWorks, die nicht online stehen, herausfiltere. Jetzt gibt es Literaturverweise, die nicht online stehen. Soll ich die jetzt löschen oder stehen lassen?

**Comment by FrankvonHagel** [comment]
Die Literatur brauchen wir nur für eine bestimmte Exportvariante

**Comment by mokko** [comment]
Ne, das gibt's nicht im Moment. Ich mache nur einen Export.

**Comment by mokko** [comment]
Du kannst das ja auf deiner Seite herausfiltern. Wie wäre es damit? Ich schreibe dir mal einen Beispielfilter in xslt. Den kannst du dann selbst anwenden. Einverstanden?

**Comment by mokko** [comment]
so in der Art
saxon -s sdata\Mode\20221009\KB-zeichnetMode-join-group182397-links.onlyPub.lido.xml -x C:\m3\zml2lido\zml2lido\data\xsl\dropRelatedWorksLiterature.xsl -o o.lido.xml

**Comment by FrankvonHagel** [comment]
Wäre es möglich das Attribut für die Literaturverweise wie folgt zu definieren. 
                     <lido:conceptID lido:type="URI">http://terminology.lido-schema.org/lido00617</lido:conceptID>
                     <lido:term xml:lang="en">is documented in</lido:term>
Das wäre exakter als bisher
                     <lido:conceptID lido:type="URI">http://terminology.lido-schema.org/lido00263</lido:conceptID>
                     <lido:term xml:lang="en">is related to</lido:term>

**Comment by mokko** [comment]
Das sollte kein Problem sein

**Comment by mokko** [comment]
a0c0686..e938d3e
