### ISSUE TITLE
Todo filter script

### ISSUE THREAD

**Issue by mokko** [mokko/zml2lido#58]
lfilter -i input.lido -t feld -s

-s force overwrite with new split files.

**Comment by mokko** [comment]
def lido():
    parser = argparse.ArgumentParser(description="Little LIDO toolchain")
    parser.add_argument(
        "-c",
        "--chunks",
        help="expect the input to be multiple precisely-named chunks",
        required=False,
        action="store_true",
    )
    parser.add_argument("-i", "--input", help="zml input file", required=True)
    parser.add_argument("-j", "--job", help="pick job (e.g. smb or dd)", required=True)
    parser.add_argument(
        "-f", "--force", help="force overwrite existing lido", action="store_true"
    )
   
   args = parser.parse_args()

    if args.force:
        args.validate = True

    print(f"JOB: {args.job}")

if chunks in args:
 raise TypeError("ERROR: Filter in chunking mode not implemented yet!")
    m = LidoTool(
        Input=args.input, force=args.force, validation=args.validate, chunks=args.chunks
    )
 
m.filter(type=args.type, validate=args.validate, split=args.split)

**Comment by FrankvonHagel** [comment]
Hmmm etwas Kontext für mich?

**Comment by mokko** [comment]
Das wird ein Programm, mit dem du einzelne Elemente her ausfilterst. Aktualisiert dann noch das Split Verzeichnis. Damit du weniger tippen musst.

**Comment by mokko** [comment]
e938d3e..3e97fae
