### ISSUE TITLE
lido:displayEvent bei Ausstellung

### ISSUE THREAD

**Issue by FrankvonHagel** [mokko/zml2lido#59]
wieso steht im lido:displayEvent der lange Text:
```<lido:displayEvent xml:lang="de">Helen Ernst, Berlin, Das verborgene Museum e. V., 1994-07-15 - 1994-08-28, Lipp Hdz 644, Zeichnung, Frauen in Nachmittagskleidern, 1928, Helen Ernst (10.03.1904 - 26.03.1948)</lido:displayEvent>```

war da nicht ursprünglich nur deutschsprachige Begriff aus ```<lido:term xml:lang="de">Herstellung</lido:term>```des EventTypes?

**Comment by mokko** [comment]
Ist das nicht der Literaturverweis, den du in DisplayEvent haben wolltest?

**Comment by FrankvonHagel** [comment]
Nein das ist ja das DISPLAY des Events"Herstellung oder Fund oder was auch immer" der lange Literaturverweis müsste in 

<lido:relatedWork>
       <lido:displayObject>Hübner, Hans 2002</lido:displayObject>
stehen aber da ist nur die Kurzform

**Comment by mokko** [comment]
Guck dir mal issue 55 an. Da steht drin, dass ich in displayEvent schreiben soll. Wenn ich das, woandershin schreiben soll, dann sag wohin.

**Comment by FrankvonHagel** [comment]
Du hast recht... Mein Fehler. Es geht um das Event Ausstellung und da wäre es richtig genau wie bei anderen Event zu bauen... Also Display wäre "Ausstellung":
Der Ausstellungstitel käme m.E. in "lido:eventName
Der Ort in "lido:eventPlace
das Datum in "lido:eventDate
aber ich befürchte so genau hast du die Daten gar nicht.

Dazu bräuchtest Du ExhTitleGrp.TitleXpd 
dein Titel ist viel lä#nger
 <lido:displayEventxml:lang="de">Helen Ernst, Berlin, Das verborgene Museum e. V., 1994-07-15 - 1994-08-28, Lipp Hdz 644, Zeichnung, Frauen in Nachmittagskleidern, 1928, Helen Ernst (10.03.1904 - 26.03.1948)</lido:displayEvent>

siehe hier:
![image](https://user-images.githubusercontent.com/25053863/197787001-d05d01f6-404f-4153-964e-145ca90e7d7c.png)

**Comment by mokko** [comment]
Ich habe einen String. Ich könnte den Aufsplitten in Teile. Aber da sind wohl nicht immer die gleichen Elemente in der gleichen Reihenfolgen. Also was soll ich machen?

Ich kann Ausstellung in displayEvent schreiben und den Rest in lido:eventName.

```
<lido:eventSet>
   <lido:displayEvent xml:lang="de">Ausstellung</lido:displayEvent>
   <lido:event>
      <lido:eventType>
         <lido:conceptID lido:type="URI" lido:source="LIDO-Terminologie">http://terminology.lido-schema.org/lido00225</lido:conceptID>
         <lido:term xml:lang="de">Ausstellung (Aktivität)</lido:term>
         <lido:term xml:lang="en">Exhibition (Activity)</lido:term>
      </lido:eventType>
      <lido:eventName>
         <lido:appellationValue>PPP, Berlin, Kunstbibliothek, Kulturforum/Ausstellungsraum KB, 2009-05-07 - 2009-08-09, Lipp Hdz 649, Zeichnung, Androgyne feminine Kleidung, 1928, Helen Ernst (10.03.1904 - 26.03.1948)</lido:appellationValue>
      </lido:eventName>
   </lido:event>
</lido:eventSet>
```

**Comment by mokko** [comment]
Soll ich das jetzt schließen?

**Comment by mokko** [comment]
a0c0686

**Comment by FrankvonHagel** [comment]
Lieber Maurice, schau mal hier. Da sind die Felder für 
Ausstellungen:  ExhTitleGrp.TitleClb], [ExhVenueDetailsTxt], [ExhBeginDateDat]–[ExhEndDateDat] 
und 
Literatur: [LitReferenceShortTxt]: [LitCitationClb], [ObjLiteratureRef[PageRefTxt], [ObjLiteratureRef[PicturePageTxt]], [ObjLiteratureRef[CatalogueNumberTxt 
benannt. Sind diese nicht im Objekt-API Datenumfang enthalten?

**Comment by mokko** [comment]
Der Deal war zwischen uns war, dass ich Felder/Inhalte aus Objektmodul zusammenschreibe. Jetzt willst dass ich mehr Module herunterlade. Ich hatte dir gleich am Anfang gesagt, dass ich jetzt nicht mehr machen kann. Also habe ich das jetzt alles umsonst gemacht.
