### ISSUE TITLE
<lido:displayActorInRole>

### ISSUE THREAD

**Issue by FrankvonHagel** [mokko/zml2lido#60]
Im <lido:displayActorInRole> weichen wir immer noch von der Vorgabe für die Webseite ab. Bekommst Du die Wiederholung des Events da raus? Also ohne
"Herstellung: "
bei DS 1412264

lido:displayActorInRole>Helen Ernst (10.03.1904 - 26.03.1948), Zeichnerin</lido:displayActorInRole>

wäre soviel besser https://id.smb.museum/object/1412264/frauen-in-nachmittagskleidern

**Comment by mokko** [comment]
Das sollte wohl gehen. Ich meine mich zu erinnern, das schon mal gemacht zu haben. Ist aber nicht im Code.

**Comment by mokko** [comment]
81da760 erledigt
