### ISSUE TITLE
Rechte Digital Asset

### ISSUE THREAD

**Issue by FrankvonHagel** [mokko/zml2lido#63]
Lieber Maurice, ich vermute du schreibst die Rechteangaben zum Digital Asset noch "hart" rein.  
Beispiel KK Objekt (de-MUS-018511/1059178) Digital Asset 5022232 hat im MDS die Rechteangabe Public Domain Mark 1.0
Im Export steht aber das alte recht (cc-by-sa-nc) 

1. Könntest Du stattdessen den eingetragenen Wert auslesen - WENN VORHANDEN? und wenn NICHT vorhanden denn cc-by-sa-nc eintragen?
2. Die  <lido:resourceDescription> WEGLASSEN wenn der Entrag "bpk Kopie freigestellt" lautet?

Screenshot MDS
[Bildrecht vvg.pdf](https://github.com/mokko/zml2lido/files/9870351/Bildrecht.vvg.pdf)

         <lido:resourceWrap>
            <lido:resourceSet lido:sortorder="1">
               <lido:resourceID lido:label="Bild" lido:type="local" lido:source="SMB/ObjID/AssetID">de-MUS-018511/1059178/5022232</lido:resourceID>
               <lido:resourceRepresentation lido:type="Provided image">
                  <lido:linkResource lido:formatResource="image/jpeg">https://id.smb.museum/digital-asset/5022232</lido:linkResource>
               </lido:resourceRepresentation>
               <lido:resourceType>
                  <lido:term xml:lang="EN">image</lido:term>
               </lido:resourceType>
               <lido:resourceDescription>bpk Kopie freigestellt</lido:resourceDescription>
               <lido:rightsResource>
                  <lido:rightsType>
                     <lido:conceptID lido:source="CC" lido:type="URI">http://creativecommons.org/by-nc-sa/4.0/</lido:conceptID>
                     <lido:term lido:addedSearchTerm="no">Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0)</lido:term>
                  </lido:rightsType>
                  <lido:rightsHolder>
                     <lido:legalBodyID lido:type="concept-ID" lido:source="ISIL (ISO 15511)">de-MUS-018511</lido:legalBodyID>
                     <lido:legalBodyName>
                        <lido:appellationValue>Kupferstichkabinett, Staatliche Museen zu Berlin</lido:appellationValue>
                     </lido:legalBodyName>
                     <lido:legalBodyWeblink>https://www.smb.museum/museen-einrichtungen/kupferstichkabinett/home/</lido:legalBodyWeblink>
                  </lido:rightsHolder>
                  <lido:creditLine>Staatliche Museen zu Berlin, Kupferstichkabinett / Jörg P. Anders</lido:creditLine>
               </lido:rightsResource>
            </lido:resourceSet>
         </lido:resourceWrap>

**Comment by mokko** [comment]
Das ist ja schön und gut. Jetzt finde ich allerdings Fälle bei denen es mehrere Lizenzen gibt. Beispiel
```
<repeatableGroup name="MulRightsGrp" size="2">
  <repeatableGroupItem id="10771941">
    <dataField dataType="Date" name="EndDateDat">
      <value>2022-08-26</value>
      <formattedValue language="en">26/08/2022</formattedValue>
    </dataField>
    <dataField dataType="Clob" name="NotesClb">
      <value>Von HR am 2.8.22 aus Inhaber nach Lizenz übertragen</value>
    </dataField>
    <vocabularyReference name="LicenceVoc" id="79802" instanceName="MulRightsLicenceVgr">
      <vocabularyReferenceItem id="4823976" name="CC BY-NC-SA 4.0">
        <formattedValue language="en">CC BY-NC-SA 4.0</formattedValue>
      </vocabularyReferenceItem>
    </vocabularyReference>
    <vocabularyReference name="TypeVoc" id="33621" instanceName="MulRightsTypeVgr">
      <vocabularyReferenceItem id="1816004" name="Bildrechte">
        <formattedValue language="en">Bildrechte</formattedValue>
      </vocabularyReferenceItem>
    </vocabularyReference>
  </repeatableGroupItem>
  <repeatableGroupItem id="18042739">
    <dataField dataType="Date" name="BeginDateDat">
      <value>2022-08-26</value>
      <formattedValue language="en">26/08/2022</formattedValue>
    </dataField>
    <vocabularyReference name="LicenceVoc" id="79802" instanceName="MulRightsLicenceVgr">
      <vocabularyReferenceItem id="4823977" name="Public Domain Mark 1.0">
        <formattedValue language="en">Public Domain Mark 1.0</formattedValue>
      </vocabularyReferenceItem>
    </vocabularyReference>
    <vocabularyReference name="TypeVoc" id="33621" instanceName="MulRightsTypeVgr">
      <vocabularyReferenceItem id="1816004" name="Bildrechte">
        <formattedValue language="en">Bildrechte</formattedValue>
      </vocabularyReferenceItem>
    </vocabularyReference>
  </repeatableGroupItem>
</repeatableGroup>
```
Ich nehme mal an, dass so ein Eintrag in RIA sinnvoll ist, obwohl ich da nicht sicher bin. Jedenfalls könnte ja jemand die Rechte zum historischen Zeitpunkt x dokumentieren wollen. 

In diesem Fall soll ich die aktuellere Lizenz nehmen, nehme ich. Beschrieben hier als EndDate 2022-08-26 BeginDate 2022-08-26. Ich muss also das größte Datum von BeginDate nehmen. Oder kein Date, wenn es nicht ausgefüllt wird.

**Comment by mokko** [comment]
86f2b89..3eba9e9

**Comment by FrankvonHagel** [comment]
Ist das vom KK Objekt (de-MUS-018511/1059178) und dem  Digital Asset 5022232

**Comment by mokko** [comment]
Ich habe IDS nicht mit kopiert, kann also nicht mehr einfach sagen, von welchem Beispiel. Mein Beispiel illustriert Fall, wo eine Resource mehrere Lizenzen hat, die zeitlich gedacht sind. 

Das xslt nimmt jetzt einfach nur den letzten Eintrag, hoffend, dass der neueste ist. Bin aber nicht sicher, ob das immer so ist.
