### ISSUE TITLE
relatedWorkSet in DDB

### ISSUE THREAD

**Issue by mokko** [mokko/zml2lido#70]
FvH schreibt
"relatedWorkSet: objectID sollte hier nur mitgegeben werden, falls das entsprechende Objekt bereits in der DDB/Teil der aktuellen Lieferung ist. Andernfalls kommt es beim Ingest zu einer Fehlermeldung. Bei den verbliebenen objectID müsste <ISIL>/ davor ergänzt werden (wie bei der lidoRecID), damit DDB-intern die Verknüpfung hergestellt werden kann => da müsstet ihr den Überblick haben, welche Objekte bereits in der DDB sind"

- Ich habe extra solche relatedWorkSet herausgefiltert, die nicht online stehen. Außer bei Literatur, die stehen nie online und die wollte Frank trotzdem haben.

- Ich muss überhaupt keinen Überblick haben, welche Objekte in der DDB sind. 
- Im Ernst: Wie sollen das denn die Institutionen können? 
- ISIL könnte ich vielleicht ergänzen, ist aber wohl nicht trivial. Ich bin nicht sicher, ob ich diese Info (bzw. verwaltende Institution) aus dem Objekte-Modul-DS bekomme.
- Wenn die DDB nicht mit unseren korrekten Informationen umgehen kann, kann sie gerne die relatedWorkSet ignorieren. Oder du kannst sie raus löschen. Andere kurzfristige Lösung sehe ich nicht.

**Comment by mokko** [comment]
PS: Ich habe dich gestern oder so als Mitarbeiter eingetragen. Guck mal, ob du jetzt Issues wieder öffnen kannst.

Ich schließe den Issue, weil ich ihn für erledigt halte.

**Comment by FrankvonHagel** [comment]
Wird das Issue durch einfaches schreiben automatisch geöffnet?

**Comment by FrankvonHagel** [comment]
Damit kann ich dann aber nur neue Issues schreiben keine alten öffen

**
![image](https://user-images.githubusercontent.com/25053863/200295862-0ae72c8b-1598-4b7b-8e87-4e1881474da7.png)

**

**Comment by mokko** [comment]
Aha, ich verstehe. Bei mir steht unten beim Absenden eines Textes auf der
github neben Absenden auch eine Box, in der man den Issue wieder öffnen
kann. Guck mal, ob du sie siehst. Wenn nicht, weiß ich auch nicht. Neue
Issues sind vielleicht sowieso besser. Du kannst URL des alten Issues
einfügen. Dann bleibt inhaltlicher Bezug bestehen.
