### ISSUE TITLE
Object WorkType - Sprachangabe en falsch

### ISSUE THREAD

**Issue by FrankvonHagel** [mokko/zml2lido#74]
Ausgabe KB-Plakate Datensätze (Beispiel de-MUS-814517/2763628)
schau einmal hier:, das müsste doch de sein, oder? Im local 4288846 steht auch nur ein de. (ist die Spracheingabe von Dir in dem Knoten fest eingetragen, dann kann das manuell ändern)

```
 <lido:objectWorkType lido:type="Sachbegriff">
    <lido:conceptID lido:source="RIA:Sachbegriff" lido:type="local">4288846</lido:conceptID>
    <lido:term xml:lang="en">Entwurf (Plakat)</lido:term>
 </lido:objectWorkType>
 <lido:objectWorkType lido:type="Sachbegriff">
    <lido:conceptID lido:source="RIA:Sachbegriff" lido:type="local">4288846</lido:conceptID>
    <lido:term xml:lang="en">Entwurf (Plakat)</lido:term>

```

**Comment by mokko** [comment]
Sachbegriff kommt aus z:vocabularyReference[@name='TechnicalTermVoc']
Beispiel aus Mode
```
<vocabularyReference name="TechnicalTermVoc" id="61702" instanceName="ObjTechnicalTermVgr">
  <vocabularyReferenceItem id="4289348" name="Zeichnung">
    <formattedValue language="en">drawing</formattedValue>
  </vocabularyReferenceItem>
</vocabularyReference>
```

es gibt also durchaus Englische Einträge. Diese sind im obigen Beispiel auch korrekt qualifiziert. Ich kann also nicht hardgecodete Sprachauszeichnung de verwenden.

Beispiel aus Plakate
```
<vocabularyReference name="TechnicalTermVoc" id="61702" instanceName="ObjTechnicalTermVgr">
  <vocabularyReferenceItem id="4288846" name="Entwurf (Plakat)">
    <formattedValue language="en">Entwurf (Plakat)</formattedValue>
  </vocabularyReferenceItem>
</vocabularyReference>
```
Auszeichnung in RIA ist falsch. Kann ich also nichts richtiger mappen als es schon ist.

**Comment by mokko** [comment]
Ich kann 
- XML:lang weg lassen, 
- dynamisch hinschreiben, was in zml steht oder
- Immer de oder en schreiben
