### ISSUE TITLE
 Object WorkType -  lido:type="ObjTechnicalTermClb" ?

### ISSUE THREAD

**Issue by FrankvonHagel** [mokko/zml2lido#75]
Beispiel de-MUS-814517/2763628

Ich verstehe - glaube ich - wie die Ausgabe zustande kommt, könntest du aber bitte da auch die  xml:lang="de"> angeben wie im der entsprechenden  <lido:classification lido:type="RIA:Sachbegriff"> (Es siehtbesser aus, auch wenn ich nicht weiß wo das "de" herkommt?)

            <lido:objectWorkTypeWrap>
               <lido:objectWorkType lido:type="ObjTechnicalTermClb">
                  <lido:term>Fotografie und Moderne Kunst -&gt; Fotografie -&gt; Ausgrabung -&gt; Objekt -&gt; Stein</lido:term>
               </lido:objectWorkType>
            </lido:objectWorkTypeWrap>

**Comment by mokko** [comment]
Info sieht in RIA so aus
```
<dataField dataType="Clob" name="ObjTechnicalTermClb">
  <value>Fotografie und Moderne Kunst -&gt; Fotografie -&gt; Topografie -&gt; Landschaft</value>
</dataField>
 ```
Hat also KEINE Sprachauszeichnung. Ich schreibe jetzt hardcoded de hinein, weil ich annehme, dass meisten RIA-Nutzer dieses Feld in de ausfüllen.

**Comment by mokko** [comment]
Sieht jetzt so aus:
```
<lido:objectWorkTypeWrap>
   <lido:objectWorkType lido:type="ObjTechnicalTermClb">
      <lido:term xml:lang="de">Fotografie und Moderne Kunst -&gt; Fotografie -&gt; Topografie -&gt; Landschaft</lido:term>
   </lido:objectWorkType>
</lido:objectWorkTypeWrap>
```

**Comment by mokko** [comment]
f877a5e..5345b67

**Comment by FrankvonHagel** [comment]
Werde mit etwas Notepad++ Zauberei nacharbeiten.... :-)
