### ISSUE TITLE
lido:eventPlace in der KB

### ISSUE THREAD

**Issue by FrankvonHagel** [mokko/zml2lido#77]
Es fehlen die Ortsangaben in Datensätzen wenn der Ortstyp
Druckort
Entstehungsort
faktischer Entstehungsort 
Entstehungsort stilistisch
Verwendungsort: 
dargestellter Ort
ist. Könntest Du bitte diese Ortstypen in der Transformation berücksichtigen?

**Comment by FrankvonHagel** [comment]
Auch beim KB Modebild fehlen dei Orte im EventPlace Beispiel ID 1412505 
![grafik](https://user-images.githubusercontent.com/25053863/202203755-6589992a-eb23-4422-a7df-92aec1d78d31.png)
![grafik](https://user-images.githubusercontent.com/25053863/202203857-0b11b065-845c-40c4-a071-15cdf131e1cc.png)

**Comment by mokko** [comment]
Das sind ja Orte in Events, d.h. Enstehungsort geht in Herstellung, in welches Ereignis soll Verwendungsort? dargestellter kann auch in Herstellung. Korrekt?

**Comment by mokko** [comment]
Ich füge also die Ortstypen zu den herstellenden Ortstypen hinzu.

Was ich dann in LIDO erhalte ist etwas wie
```
<lido:eventPlace lido:sortorder="5">
   <lido:displayPlace xml:lang="de" lido:encodinganalog="PlaceVoc">Berlin</lido:displayPlace>
   <lido:place>
      <lido:placeID lido:type="internal">2282422</lido:placeID>
      <lido:namePlaceSet>
         <lido:appellationValue>Berlin</lido:appellationValue>
      </lido:namePlaceSet>
   </lido:place>
</lido:eventPlace>
```

Basierend auf zml wie
```
<repeatableGroup name="ObjGeograficGrp" size="1">
<repeatableGroupItem id="49761328">
  <dataField dataType="Varchar" name="ModifiedByTxt">
    <value>KB_HR</value>
  </dataField>
  <dataField dataType="Date" name="ModifiedDateDat">
    <value>2020-11-05</value>
    <formattedValue language="en">05/11/2020</formattedValue>
  </dataField>
  <dataField dataType="Long" name="SortLnu">
    <value>5</value>
    <formattedValue language="en">5</formattedValue>
  </dataField>
  <vocabularyReference name="GeopolVoc" id="61663" instanceName="ObjGeopolVgr">
    <vocabularyReferenceItem id="4399196" name="Stadt">
      <formattedValue language="en">Stadt</formattedValue>
    </vocabularyReferenceItem>
  </vocabularyReference>
  <vocabularyReference name="PlaceVoc" id="30288" instanceName="GenPlaceVgr">
    <vocabularyReferenceItem id="2282422" name="Berlin">
      <formattedValue language="en">Berlin</formattedValue>
    </vocabularyReferenceItem>
  </vocabularyReference>
  <vocabularyReference name="TypeVoc" id="52617" instanceName="ObjGeographicTypeVgr">
    <vocabularyReferenceItem id="4366945" name="Herstellungsort">
      <formattedValue language="en">Herstellungsort</formattedValue>
    </vocabularyReferenceItem>
  </vocabularyReference>
</repeatableGroupItem>
```

Da stellt sich doch die Frage, ob wir den Ort in LIDO auch wenigstens mit dem Ortstyp beschreiben können. Also Blick in die Spezifikation.

**Comment by mokko** [comment]
Also zu erst nur neue Ortstypen einfügen
```
<xsl:variable name="herstellendeOrtstypen" select="
	'dargestellter Ort',
	'Druckort',
	'Entstehungsort',
	'Entstehungsort stilistisch',
	'faktischer Entstehungsort',
	'Herstellungsort',
"/>
```
7ec2a0b..b25e69b

**Comment by mokko** [comment]
Jeder Datumstyp kann nur in einem Event-Typ erscheinen. Herstellungsdatum kommt in Event Herstellung (und lässt sich dort funktional übrigens nicht weiter in LIDO beschreiben). D.h. es Herstellungsdatum erscheint dann in keinem anderen Eventtyp.

Funddatum kann also auch in Event Fund erscheinen.

Nutzung haben wir momentan nicht als Eventtyp.

Warum Druckort dem Entwurfsdatum zugeordnet werden soll erschließt sich mir nicht. 

Ich kann Druckort wohl der Herstellung zuordnung. Bei Plakaten sollte das zutreffen. Ob das immer zutrifft, weiß ich nicht.
