### ISSUE TITLE
Maßangaben

### ISSUE THREAD

**Issue by FrankvonHagel** [mokko/zml2lido#80]
Kann es sein, das beim measurementSet für Passepartout die Breite und Höhe verdreht werden? siehe angehängte Datei und 
<SNIPPED>
            <lido:objectMeasurementsWrap>
               <lido:objectMeasurementsSet>
                  <lido:displayObjectMeasurements xml:lang="de">Passepartout: 53 x 39 cm</lido:displayObjectMeasurements>
                  <lido:displayObjectMeasurements xml:lang="en">53 x 39 cm</lido:displayObjectMeasurements>
                  <lido:objectMeasurements>
                     <lido:measurementsSet>
                        <lido:measurementType xml:lang="de">Passepartout</lido:measurementType>
                        <lido:measurementUnit xml:lang="de">cm</lido:measurementUnit>
                        <lido:measurementValue xml:lang="de">39 x 53</lido:measurementValue>
                     </lido:measurementsSet>
                     <lido:measurementsSet>
                        <lido:measurementType xml:lang="de">Passepartout</lido:measurementType>
                        <lido:measurementUnit xml:lang="en">cm</lido:measurementUnit>
                        <lido:measurementValue xml:lang="en">39 x 53</lido:measurementValue>
                     </lido:measurementsSet>
                  </lido:objectMeasurements>
               </lido:objectMeasurementsSet>
               <lido:objectMeasurementsSet>
                  <lido:displayObjectMeasurements xml:lang="de">Blattmaß: ca. 23,9 x 21,9 cm</lido:displayObjectMeasurements>
                  <lido:displayObjectMeasurements xml:lang="en">ca. 23.9 x 21.9 cm</lido:displayObjectMeasurements>
                  <lido:objectMeasurements>
                     <lido:measurementsSet>
                        <lido:measurementType xml:lang="de">Blattmaß</lido:measurementType>
                        <lido:measurementUnit xml:lang="de">cm</lido:measurementUnit>
                        <lido:measurementValue xml:lang="de">23,9 x 21,9</lido:measurementValue>
                     </lido:measurementsSet>
                     <lido:measurementsSet>
                        <lido:measurementType xml:lang="en">Sheet size</lido:measurementType>
                        <lido:measurementUnit xml:lang="en">cm</lido:measurementUnit>
                        <lido:measurementValue xml:lang="en">23.9 x 21.9</lido:measurementValue>
                     </lido:measurementsSet>
                  </lido:objectMeasurements>
               </lido:objectMeasurementsSet>
</SNIPPED>

**Comment by mokko** [comment]
Passepartout hat Width x Height. Vgl. Unten. Wenn du es andersherum haben möchtest, drehe ich es um. 

```<xsl:when test="$this eq 'Passepartout'">
				<xsl:value-of select="normalize-space(../../../z:dataField[@name='WidthNum']/z:value)"/>
				<xsl:text> x </xsl:text>
				<xsl:value-of select="normalize-space(../../../z:dataField[@name='HeightNum']/z:value)"/>
			</xsl:when>
			<xsl:when test="$this eq 'Passepartoutmaß'">
				<xsl:value-of select="normalize-space(../../../z:dataField[@name='WidthNum']/z:value)"/>
				<xsl:text> x </xsl:text>
				<xsl:value-of select="normalize-space(../../../z:dataField[@name='HeightNum']/z:value)"/>
			</xsl:when>
			<xsl:when test="$this eq 'Passepartout Standardformat'">
				<xsl:value-of select="normalize-space(../../../z:dataField[@name='WidthNum']/z:value)"/>
				<xsl:text> x </xsl:text>
				<xsl:value-of select="normalize-space(../../../z:dataField[@name='HeightNum']/z:value)"/>
			</xsl:when>```

**Comment by FrankvonHagel** [comment]
[1412264.lido - Kopie.xml.csv](https://github.com/mokko/zml2lido/files/10065000/1412264.lido.-.Kopie.xml.csv)
Beispiel 1412264.lido.xml (einfach.csv entfernen)
Was mich verwndert ist das im Display die Anzeige "Passepartout: 53 x 39 cm" erfolgt und im Measurement dann "39 x 53" .

**Comment by mokko** [comment]
display gibt es zweimal de und en
- de Version hat den Wert aus RIA Feld 
z:moduleReference[
						@name='TypeDimRef']/z:moduleReferenceItem/z:formattedValue
- en hat den Wert aus PreviewENVrt

Ich sollte wahrscheinlich auch in de den Wert aus PreviewVrt eintragen. Das mache ich mal. Davon unabhängig guck dir bitte mal das Objekt an und entscheide was du willst.

**Comment by FrankvonHagel** [comment]
ich glaube wir reden aneinenader vorbei mich irritiert die UMDREHUNG der Zahlen im Display steht 53*39 (Höhex.Breite) im Meassurement 39x53 (BreitexHöhe)
siehe 
![image](https://user-images.githubusercontent.com/25053863/203263393-8968e47b-af59-4353-9601-266d2e9ab9b5.png)

**Comment by mokko** [comment]
Ich sage: nach meiner Recherche scheint Breite x Höhe (also x mal y) die übliche Repräsentationsform zu sein (in der wirklichen Welt abseits von M+) und dass du mir klar sagen sollst, was Du haben willst.

im Display-Feld steht im Übrigen, was M+ als Displaywert ausgibt. Ich will das nicht aufsplittern und umdrehen. Für alles präzisere sind die nicht-display-Felder da.

**Comment by mokko** [comment]
Was den Konflikt etwas entschärfen würde wäre, wenn wir in Lido wenigstens sagen würden, was Länge und Breite wäre. Da müsste bei den Details stehen nicht nur „Passepartout“ sondern  „Passepartout (Breite x Länge)“ als Typ. Einverstanden?

**Comment by mokko** [comment]
Oder du redest mit Helen, dass sie Preview Werte in Ria ändert.
