### ISSUE TITLE
Der englische Term für Blattmaß ist anscheinend noch nicht definiert

### ISSUE THREAD

**Issue by FrankvonHagel** [mokko/zml2lido#81]
<lido:measurementType xml:lang="de">Blattmaß</lido:measurementType>
.....
im englsichsprachigen Set wird 
<lido:measurementType xml:lang="de">Blattmaß

ausgegeben Es sollte 
                        <lido:measurementType xml:lang="en">Sheet size</lido:measurementType>
sein.

**Comment by mokko** [comment]
Wir hatten zusammen MpApi so geändert, dass die deutschen Begriffe angefordert werden. Deswegen mussten wir nicht alle Begriffe übersetzten, sondern haben nach ca. 5% aufgehört. Warum brauchst du die englischen Begriffe?

Heißt dass, dass du MpApi nicht aktualisiert hast? Ich dachte, dass hätten wir zusammen gemacht.

**Comment by FrankvonHagel** [comment]
ich denke wir haben einfach Balttmaß und Passpartout nicht übersetztn.
Ich hatte das en von Blattmaß habe ich händisch nachgearbeitet. Kann ich für Passpartout auch machen, aber der Fehler hat nicht

**Comment by mokko** [comment]
Also: ich habe mir die Stelle noch einmal im XSLT angeguckt. Ich hatte versucht, die Measurements von Deutsch auf English zu übersetzen. Jetzt haben wir die Sprache geändert mit der der Client antwortet und da geht das nicht mehr. Wir hatten auch noch nie Übersetzung für MeasurementType. Neue Ausgabe ist also durchgängig Deutsch, außer bei der displayMeasurement, was halb auf English aus dem Client herauskommt.

```
 <lido:objectMeasurementsSet>
    <lido:displayObjectMeasurements xml:lang="de">Passepartout: 53 x 39 cm</lido:displayObjectMeasurements>
    <!--
Client response includes only one language for measurementType, either 
English or German. So there is no English term available at the moment in RIA.
-->
    <lido:displayObjectMeasurements xml:lang="en">53 x 39 cm</lido:displayObjectMeasurements>
    <lido:objectMeasurements>
       <lido:measurementsSet><!--Lang attributes are dynamically created here!-->
          <lido:measurementType xml:lang="de">Passepartout</lido:measurementType>
          <lido:measurementUnit xml:lang="de">cm</lido:measurementUnit>
          <lido:measurementValue xml:lang="de">39 x 53</lido:measurementValue>
       </lido:measurementsSet>
    </lido:objectMeasurements>
 </lido:objectMeasurementsSet>
`

**Comment by mokko** [comment]
Datensatz 2887379 hat einen Eintrag Andere Maße, wo die Einheit fehlt. Ich tippe mal, dass in RIA Leerzeichen eingetragen wurden, habe aber nicht nachgeguckt. Eintrag wird jetzt nicht angezeigt, sollte aber datengebende Institution korrigieren. Lido erlaubt keinen Eintrag von measurementValue ohne Einheit. RIA anscheinend schon.

**Comment by mokko** [comment]
04668b2..5246509

**Comment by mokko** [comment]
Soweit ich das sehe, laden wir im Moment immer eine Sprache runter. Früher war en angefordert, neuerdings ist das de
