### ISSUE TITLE
Geschlecht Person aus Personenmodul

### ISSUE THREAD

**Issue by FrankvonHagel** [mokko/zml2lido#82]
DS 3012699
Im Export wurde 
                           <lido:genderActor xml:lang="en">weiblich</lido:genderActor>
ausgeliefert. Ich habe in MDS de als bevorzugt und andere Sprachversionen als "nicht bevorzugt" ausgezeichnet.
Das hat auch nicht geholfen... Es wird in lang immer en eingetragen.
[3012699.lido-xml.zip](https://github.com/mokko/zml2lido/files/10075887/3012699.lido-xml.zip)

**Comment by mokko** [comment]
Wir haben das gerade umgestellt und de angefragt. Jetzt gibt es halt an einigen Stellen Fehler, wo wir fest verdrahtete Lösungen, die für die Ausgabe in en gemacht waren. Die müssen wir jetzt einmal dynamisch machen, damit es wieder funktioniert, dann ist es aber deutlich besser als vorher.

**Comment by mokko** [comment]
31ca152

**Comment by mokko** [comment]
Weitere Qualis in der Umgebung dynamisiert. 9650a97
