### ISSUE TITLE
Ausgabe Datierung

### ISSUE THREAD

**Issue by FrankvonHagel** [mokko/zml2lido#83]
DS 3012699
Ausgeben wird arround und Sprachauszeichnung lang="de" Das verstehe ich nicht denn?
```
<lido:eventDate>
   <lido:displayDate xml:lang="de">around</lido:displayDate>
</lido:eventDate>
```
Denn im MDS ist sowohl Dat.(Text) wie auch Datum von und Datum bis ausgefüllt. Siehe image

![image](https://user-images.githubusercontent.com/25053863/203559712-87fb06bf-7274-4c2f-94bd-64364c494f59.png)

[3012699.lido-xml.zip](https://github.com/mokko/zml2lido/files/10075928/3012699.lido-xml.zip)

**Comment by mokko** [comment]
Ich habe jetzt schon etliche Male geschrieben, warum das so ist. Beim nächsten Mal mündlich.

**Comment by mokko** [comment]
Du hast einen Fehler im DS 3012699, postet aber ein Bild von einem anderen DS aus RIA.

So sieht in RIA XML aus:
```
<repeatableGroup name="ObjDateGrp" size="1">
<repeatableGroupItem id="52414860">
<dataField dataType="Varchar" name="DateTxt">
  <value>1928</value>
</dataField>
<dataField dataType="Varchar" name="PreviewOther1Txt">
  <value>around</value>
</dataField>
<dataField dataType="Varchar" name="PreviewOther2Txt">
  <value>um</value>
</dataField>
<dataField dataType="Varchar" name="PreviewTxt">
  <value>around</value>
</dataField>
<dataField dataType="Long" name="SortLnu">
  <value>1</value>
  <formattedValue language="de">1</formattedValue>
</dataField>
<virtualField name="PreviewVrt">
  <value>um 1928</value>
</virtualField>
<virtualField name="PreviewENVrt">
  <value>around 1928</value>
</virtualField>
```

**Comment by mokko** [comment]
1eb5a11
