### ISSUE TITLE
Abbruch Export KB-Plakate (zml2lido)

### ISSUE THREAD

**Issue by FrankvonHagel** [mokko/zml2lido#85]
Lieber Maurice  bei mir bricht die Transformation von KB-Plakate zusammen (update ist erfolgt). ISL und KB Mode haben ohne Probleme geklappt.

HIER DIE MELDUNG
H:\Documents\py\zml2lido>
H:\Documents\py\zml2lido>lido -j smb -i H:\Documents\py\MpApi\sdata\KB-Plakat\KB-Plakate\20221124\KB-Plakate-join-group64396.xml
JOB: smb
SCRIPT_DIR: \\FS0002\Home\MDFRAHAG\Documents\py\zml2lido
Making new dir \\FS0002\Home\MDFRAHAG\Documents\py\zml2lido\sdata\KB-Plakate\20221124
 outdir \\FS0002\Home\MDFRAHAG\Documents\py\zml2lido\sdata\KB-Plakate\20221124
ZML2LIDO
        new
java -Xmx1450m -jar H:\Documents\py\SaxonHE10-5J\saxon-he-10.5.jar -s:H:\Documents\py\MpApi\sdata\KB-Plakat\KB-Plakate\20221124\KB-Plakate-join-group64396.xml -xsl:\\FS0002\Home\MDFRAHAG\Documents\py\zml2lido\zml2lido\data\xsl\zml2lido.xsl -o:\\FS0002\Home\MDFRAHAG\Documents\py\zml2lido\sdata\KB-Plakate\20221124\KB-Plakate-join-group64396.lido.xml
Error on line 7555915 column 17 of KB-Plakate-join-group64396.xml:
  SXXP0003   Error reported by XML parser: XML-Dokumentstrukturen müssen innerhalb derselben
  Entity beginnen und enden.: XML-Dokumentstrukturen müssen innerhalb derselben Entity
  beginnen und enden.
org.xml.sax.SAXParseException; systemId: file:/H:/Documents/py/MpApi/sdata/KB-Plakat/KB-Plakate/20221124/KB-Plakate-join-group64396.xml; lineNumber: 7555915; columnNumber: 17; XML-Dokumentstrukturen müssen innerhalb derselben Entity beginnen und enden.
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\mdfrahag\AppData\Roaming\Python\Python310\Scripts\lido.exe\__main__.py", line 7, in <module>
  File "\\FS0002\Home\MDFRAHAG\Documents\py\zml2lido\zml2lido\__init__.py", line 79, in lido
    getattr(m, args.job)()
  File "\\FS0002\Home\MDFRAHAG\Documents\py\zml2lido\zml2lido\jobs.py", line 93, in smb
    lido_fn = self.zml2lido(Input=self.Input)
  File "\\FS0002\Home\MDFRAHAG\Documents\py\zml2lido\zml2lido\lidoTool.py", line 312, in zml2lido
    return self.zml2lidoSingle(Input=Input)
  File "\\FS0002\Home\MDFRAHAG\Documents\py\zml2lido\zml2lido\lidoTool.py", line 321, in zml2lidoSingle
    self.saxon(Input=inputP, xsl=xsl["zml2lido"], output=lidoFn)
  File "\\FS0002\Home\MDFRAHAG\Documents\py\zml2lido\zml2lido\lidoTool.py", line 368, in saxon
    subprocess.run(
  File "C:\Program Files\Python310\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'java -Xmx1450m -jar H:\Documents\py\SaxonHE10-5J\saxon-he-10.5.jar -s:H:\Documents\py\MpApi\sdata\KB-Plakat\KB-Plakate\20221124\KB-Plakate-join-group64396.xml -xsl:\\FS0002\Home\MDFRAHAG\Documents\py\zml2lido\zml2lido\data\xsl\zml2lido.xsl -o:\\FS0002\Home\MDFRAHAG\Documents\py\zml2lido\sdata\KB-Plakate\20221124\KB-Plakate-join-group64396.lido.xml' returned non-zero exit status 2.

H:\Documents\py\zml2lido>

![Screnshoot-zml2lid-KB-Plakate](https://user-images.githubusercontent.com/25053863/203826013-62cb6c5c-5289-4b87-b118-c8074dea20df.jpg)

**Comment by mokko** [comment]
An den Fehler kann ich mich nicht erinnern. Ich würde denken, dass ein vorheriger Lauf des Programms in der Mitte abgebrochen wurde. Dann würde da eine unvollständige Datei liegen. Versuch' mal, ob es mit -f geht. Also
`lido -j dd -i Pfad -f`

Wenn das geht dann das gleiche noch mal mit -j SMB und ohne -f

**Comment by mokko** [comment]
Ne anders. Die join.XML Datei aus MpApi ist unvollständig. Lade die nochmal runter oder probiere es einfach noch mal. Vielleicht war sie einfach noch nicht fertig und ist inzwischen fertig geworden...
