### ISSUE TITLE
Schreibweise ISIL-Nummer in LIDO 

### ISSUE THREAD

**Issue by FrankvonHagel** [mokko/zml2lido#88]
Bitte die Schreibweise der ISIL-Nummer anpassen und vereinheitlichen. Die korrekte Schreibweise ist in Großbuchstaben zu schreiben also so: DE-MUS-007125

**Comment by mokko** [comment]
Geändert, aber nicht getestet. Versuch mal', ob's funktioniert. Also git pull.
75791f321c208417398e6b1c74eb6ae565820860

**Comment by FrankvonHagel** [comment]
Keine Ahnung wo das kleine „de“ her kam


Von: Maurice ***@***.***>
Gesendet: Dienstag, 31. Januar 2023 10:00
An: mokko/zml2lido ***@***.***>
Cc: von Hagel, Frank ***@***.***>; Author ***@***.***>
Betreff: Re: [mokko/zml2lido] Schreibweise ISIL-Nummer in LIDO (Issue #88)


Closed #88<https://github.com/mokko/zml2lido/issues/88> as completed.
