### ISSUE TITLE
ISIL in den repositorySet

### ISSUE THREAD

**Issue by mokko** [mokko/zml2lido#9]
- Zuordnung zur Einrichtung (EM / AKU): Aktuell werden die Daten nur zu den Staatlichen Museen zugeordnet (diese Zuordnung erfolgt dadurch, dass die Daten in unserem Import-Tool über die Staatliche Museen ingestiert wurden). Das technische Mapping sucht nach der ISIL im repositorySet und dort ist sie in diesem Datenbestand nicht enthalten. Wäre es möglich, die ISIL auch im repositorySet einzutragen? Ich erkundige mich parallel bei den Kolleg*innen am FIZ Karlsruhe, ob wir in Zukunft auf die ISIL im resourceSet abprüfen können (dort ist sie in diesem Datenbestand auch schon drin – das ist laut der Anforderungen an die Lieferdaten auch der Ort, an dem der Identifikator für den Datengeber enthalten sein muss).

**Comment by FrankvonHagel** [comment]
sorry kann irgendwie keine Datei hochladen...

**Comment by mokko** [comment]
fixed
