### ISSUE TITLE
Fehler Rechte URI Inhalt zu term Erläuterung

### ISSUE THREAD

**Issue by FrankvonHagel** [mokko/zml2lido#91]
Hallo Maurice an der Stelle REchteauszeichnung im ressource Set gibt es einen Fehler.

Die URL is korrekt aber die "Übersetzung" der Term ist noch der alte statische:

<lido:type="URI">https://creativecommons.org/publicdomain/mark/1.0/</lido:conceptID>
<lido:term lido:addedSearchTerm="no">Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0)</lido:term>

Korrekt wäre: 
<lido:type="URI">https://creativecommons.org/publicdomain/mark/1.0/</lido:conceptID>
<lido:term lido:addedSearchTerm="no">Public Domain Mark 1.0 (PD</lido:term>

**Comment by mokko** [comment]
Ich kann diesen Fehler nicht im Mapping finden. Geb' mir bitte ein Beispiel. Mindestens welches Recht betroffen ist, am besten einen ganzen Datensatz.
