### ISSUE TITLE
Ressource Set Benennung der einzelnen Abbildung

### ISSUE THREAD

**Issue by FrankvonHagel** [mokko/zml2lido#92]
Bitte den Inhalt des Feldes "DigitalAsste | Funktion = MulCategoryVoc " ausgeben, also z.B. Standardbild

Im LIDO sollte es im Element "lido:resourceSet | lido:resourceRelType | @lido:term |" stehen

**Comment by mokko** [comment]
```
        <vocabularyReference name="MulCategoryVoc" id="30330" instanceName="MulCategoryVgr">
          <vocabularyReferenceItem id="67695" name="Standardbild">
            <formattedValue language="de">Standardbild</formattedValue>
          </vocabularyReferenceItem>
        </vocabularyReference>
```

**Comment by mokko** [comment]
In Lido sieht das jetzt so aus. Das ist was du haben willst?

resourceRelType: The relationship of the resource to the object / work being described.
```
<lido:resourceRelType>
  <lido:conceptID lido:type="internal">31041</lido:conceptID>
  <lido:term xml:lang="de">Digitale Aufnahme</lido:term>
</lido:resourceRelType>
```

**Comment by mokko** [comment]
FvH: "Wichtig ist das wir das Standardbild erkennen um dies als bevorzugte Abbildung anzeigen zu können."

Das Feld Funktion speichert nicht zuverlässig die gewünschte Information.
Also Mapping oben also wohl falsch und ich kann es wieder löschen.

**Comment by mokko** [comment]
Aus dem Objekte-Modul
```
<moduleReference name="ObjMultimediaRef" targetModule="Multimedia" multiplicity="M:N" size="2">
    <moduleReferenceItem moduleItemId="2848855" seqNo="0">
      <formattedValue language="de">IV Ca Nls 40.jpg, Repro Digitalisat</formattedValue>
      <dataField dataType="Boolean" name="ThumbnailBoo">
        <value>true</value>
        <formattedValue language="de">ja</formattedValue>
      </dataField>
      <dataField dataType="Long" name="SortLnu">
        <value>1</value>
        <formattedValue language="de">1</formattedValue>
      </dataField>
    </moduleReferenceItem>
...
```
ThumbnailBoo sagt ob es ein Standardbild ist oder nicht,

**Comment by mokko** [comment]
Nächste Frage. Wo soll nun diese Information (Standardbild) in Lido gespeichert sein? Also sicher nicht in resourceRelType, vgl. die Beispielwerte aus Lido-Spec oben.

Vielleicht in resourceSet/@sortorder? Sollen Standardbilder die sortorder 0 bekommen?

**Comment by mokko** [comment]
75791f3..d9f135d

**Comment by mokko** [comment]
6f201dd
