### ISSUE TITLE
Bug bei lido:objectPublishedID 

### ISSUE THREAD

**Issue by FrankvonHagel** [mokko/zml2lido#94]
Siehe File Test-Graphikportal-447469.lido.xml
<lido:objectPublishedID lido:type="local" lido:source="ISIL (ISO 15511)/Obj.ID">relatedWorksWrap/</lido:objectPublishedID>
ist falsch vergleiche Test-Graphikportal-3030703.lido.xml
 <lido:objectPublishedID lido:type="local" lido:source="ISIL (ISO 15511)/Obj.ID">de-MUS-018511/3030703</lido:objectPublishedID>
angehängt als zip

[Test-Graphikportal-447469.lido.xml.zip](https://github.com/mokko/zml2lido/files/10757794/Test-Graphikportal-447469.lido.xml.zip)
[Test-Graphikportal-3030703.lido.xml.zip](https://github.com/mokko/zml2lido/files/10757795/Test-Graphikportal-3030703.lido.xml.zip)

**Comment by mokko** [comment]
Lieber Frank,
ich habe jetzt den DS heruntergeladen und nach Lido konvertiert.

Dann bekomme ich Folgendes:
```
<lido:lidoRecID lido:source="ISIL (ISO 15511)/Obj.ID" lido:type="local">DE-MUS-018511/447469</lido:lidoRecID>
<!--objectPublishedID exists only if record has been published at SMB-Digital / recherche.smb. Publishing timestamp exists only for records that have been published since 2020-12-14.-->
<lido:objectPublishedID lido:type="local" lido:source="ISIL (ISO 15511)/Obj.ID">DE-MUS-018511/447469</lido:objectPublishedID>
```

Ich kann also den Fehler nicht finden. Wann tritt er auf?
