### ISSUE TITLE
Classification: @source instead of @type

### ISSUE THREAD

**Issue by FrankvonHagel** [mokko/zml2lido#95]
Grundsätzlich sollte in Type nur "URI" oder "local" stehen. Ausnahme ist "europeana:type" weil das die EUROPEANA so vorschreibt. 

Für die andern aus MDS stammenden Begriffe sollten wir besser das  Attribut Source verwenden (analog AAT) also
statt <lido:classification lido:type="RIA:Sachbegriff"> besser <lido:classification lido:source="RIA:Sachbegriff" lido:type="local">
statt <lido:classification lido:type="Sammlung"> besser <lido:classification lido:source="Sammlung" lido:type="local">

Wenn wir an die ID im Vokabularmodul herankommen siehe
  <lido:objectWorkTypeWrap>
               <lido:objectWorkType lido:type="Sachbegriff">
                  <lido:conceptID lido:source="RIA:Sachbegriff" lido:type="local">428934
[447469.lido - Kopie xml.txt](https://github.com/mokko/zml2lido/files/10812348/447469.lido.-.Kopie.xml.txt)
8</lido:conceptID>
                  <lido:term xml:lang="de">Zeichnung</lido:term>
               </lido:objectWorkType>
ist das natürlich ideal

**Comment by FrankvonHagel** [comment]
[447469.lido - Kopie xml.txt](https://github.com/mokko/zml2lido/files/10812350/447469.lido.-.Kopie.xml.txt)

**Comment by FrankvonHagel** [comment]
In diesem Sinne sollten wir bei SystemtikArt nicht in der Anmelkrung führen sindern wie oben

<lido:classification lido:source="SystematikArt" lido:type="local">
statt bislang:
<lido:classification>
<lido:term xml:lang="de">Zeichenkunst</lido:term>

**Comment by mokko** [comment]
AssertionError: Element '{http://www.lido-schema.org}classification', attribute '{http://www.lido-schema.org}source': The attribute '{http://www.lido-schema.org}source' is not allowed., line 34

Laut Spec darf classification kein source-Attribut besitzen. Also habe ich das in conceptID geschrieben.

```
 <lido:classification>
    <lido:conceptID lido:source="RIA:Sachbegriff" lido:type="local"/>
    <lido:term xml:lang="de">Zeichnung</lido:term>
 </lido:classification>

```

**Comment by mokko** [comment]
IDs manchmal vorhanden, etwa in ObjOrgGroupVoc
