### ISSUE TITLE
Sprachangabe in lido:displayDate 

### ISSUE THREAD

**Issue by FrankvonHagel** [mokko/zml2lido#97]
Mir ist nicht ganz klar warum hier "de" und "en" ausgegeben wird
```
  <lido:eventDate>
     <lido:displayDate xml:lang="de">um 1715/1716</lido:displayDate>
     <lido:displayDate xml:lang="en">um 1715/1716</lido:displayDate>
  </lido:eventDate>
```
[447469.lido - Kopie xml.txt](https://github.com/mokko/zml2lido/files/10813949/447469.lido.-.Kopie.xml.txt)

**Comment by mokko** [comment]
Duplicate von 
https://github.com/mokko/zml2lido/issues/102
