### ISSUE TITLE
<lido:objectMeasurementsSet>

### ISSUE THREAD

**Issue by FrankvonHagel** [mokko/zml2lido#98]
Das Display ist korrekt: 
Blattmaß ist kein measurement sondern ein  <lido:extentMeasurements>Blattmaß</lido:extentMeasurements>

Das Problem ist das in MDS hier die diversen Angaben gemixt sind wie "HöhexBreite", Objektmaß etc..
Da ich nun icht weiß ob du die einzelnen Felder  von Höhe oder Breite oder.. ansprechen kannst kann ich nicht beurteilen ob du es wie folgt umsetzen kannst:
```
<lido:objectMeasurementsSet>
    <lido:displayObjectMeasurements xml:lang="de">Blattmaß: 25,2 x 16,7 cm</lido:displayObjectMeasurements>
       <lido:displayObjectMeasurements xml:lang="en">25.2 x 16.7 cm</lido:displayObjectMeasurements>
    <lido:objectMeasurements>
        <lido:measurementsSet>
            <lido:measurementType xml:lang="de">Höhe x Breite</lido:measurementType>
            <lido:measurementUnit xml:lang="de">cm</lido:measurementUnit>
            <lido:measurementValue xml:lang="de">25.2 x 16.7</lido:measurementValue>
        </lido:measurementsSet>
        <lido:extentMeasurements>Blattmaß</lido:extentMeasurements>
    </lido:objectMeasurements>
</lido:objectMeasurementsSet>
```

[447469.lido - Kopie xml.txt](https://github.com/mokko/zml2lido/files/10813955/447469.lido.-.Kopie.xml.txt)

**Comment by mokko** [comment]
Da haben wir schon mal drüber geredet. Die Info, die du suchst, steht in RIA nicht drin. Soweit ich sehe. Deswegen kann ich sie auch nicht ausgeben.

**Comment by mokko** [comment]
Ich muss mich korrigieren. Wie Screenshot zeigt, haben die Felder in RIA Namen mit Höhe und Breite.
![grafik](https://user-images.githubusercontent.com/275316/227979073-62728c16-cedc-480d-93e3-376f8e3d6a70.png)

**Comment by mokko** [comment]
Ich schlage vor, dass ich "Blattmaß" mit "Blattmaß (Höhe x Breite)" ersetzte. Muss ich noch tun.

```
<lido:objectMeasurements>
   <lido:measurementsSet>
      <lido:measurementType xml:lang="de">Blattmaß (Höhe x Breite)</lido:measurementType>
      <lido:measurementUnit xml:lang="de">cm</lido:measurementUnit>
      <lido:measurementValue xml:lang="de">51.5 x 20.4</lido:measurementValue>
   </lido:measurementsSet>
```

**Comment by mokko** [comment]
7a398d0..01df851
